## Q1.

In [15]:
#comparison in array element-wise
#comparing 1st element of array-x with 1st element of array-y and 2nd element of array-x with 2nd element of array-y
import numpy as np
x = np.array([2,5])
y = np.array([3,5])
print(np.greater(x,y))
print(np.less(x,y))
print(np.greater_equal(x,y))
print(np.less_equal(x,y))

[False False]
[ True False]
[False  True]
[ True  True]


## Q2.

In [16]:
x = np.zeros(10) 
y = np.ones(10)
z = np.ones(10)*5 #rank 1 array
z1 = np.full((2,5) , 5) #rank 2 array
print(x)
print(y)
print(z)
print(z1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[[5 5 5 5 5]
 [5 5 5 5 5]]


## Q3.

In [4]:
x = np.array([[2,3],[4,5]])
print(np.sum(x))
print(np.sum(x , axis = 0)) #sum of each column
print(np.sum(x , axis = 1)) #sum of each row

14
[6 8]
[5 9]


## Q4.

In [17]:
print("Addition:",np.add(1.0, 4.0))
print("Subtract:",np.subtract(1.0, 4.0))
print("Multiply:",np.multiply(1.0, 4.0))
print("Divide:",np.divide(1.0, 4.0))

Addition: 5.0
Subtract: -3.0
Multiply: 4.0
Divide: 0.25


## Q5.

In [20]:
print(np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print(np.cos(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print(np.tan(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))

[0.         0.5        0.70710678 0.8660254  1.        ]
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]
